"""Add quotation fields to CustomerOrder

Revision ID: 852581342bbb
Revises: 64b388b09553
Create Date: 2026-03-01 20:48:16.727182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852581342bbb'
down_revision = '64b388b09553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quotation_items', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('quotation_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quotation_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('quotation_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('customer_response_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quoted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('responded_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('responded_at')
        batch_op.drop_column('quoted_at')
        batch_op.drop_column('customer_response_notes')
        batch_op.drop_column('quotation_notes')
        batch_op.drop_column('quotation_status')
        batch_op.drop_column('quotation_total')
        batch_op.drop_column('quotation_items')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
