"""Add branch_id to users

Revision ID: 86069c630832
Revises: b92873b62a41
Create Date: 2026-02-09 21:55:23.084753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86069c630832'
down_revision = 'b92873b62a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
